### ISSUE TITLE
Grunt errors

### ISSUE THREAD

**Issue by amelkikh** [jonadev95/kitematic-docker#1]
Hi, I try to create docker-compose config, but here some errors.
OS: Linux Mint Rose
Docker version 1.12.1, build 23cf638
docker-compose version 1.8.0, build f3628c7

Config: 

```
kitematic:
  image: jonadev95/kitematic-docker
  container_name: kitematic
  hostname: kitematic
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $HOME/.Xauthority:/root/.Xauthority
  environment:
      DISPLAY: $DISPLAY
  privileged: true
```

Log:

```
Starting kitematic
Attaching to kitematic
kitematic    | 
kitematic    | > Kitematic@0.8.2 start /opt/kitematic
kitematic    | > grunt
kitematic    | 
kitematic    | Running "download-binary:docker" (download-binary) task
kitematic    | 
kitematic    | Running "download-binary:docker-machine" (download-binary) task
kitematic    | 
kitematic    | Running "download-binary:docker-compose" (download-binary) task
kitematic    | 
kitematic    | Running "newer:babel" (newer) task
kitematic    | 
kitematic    | Running "newer:babel:dist" (newer) task
kitematic    | No newer files to process.
kitematic    | 
kitematic    | Running "less:dist" (less) task
kitematic    | File build/main.css created
kitematic    | 
kitematic    | Running "newer:copy:dev" (newer) task
kitematic    | No newer files to process.
kitematic    | 
kitematic    | Running "shell:electron" (shell) task
kitematic    | 
kitematic    | Running "watchChokidar" task
kitematic    | Waiting...
kitematic    | >> [28:0828/212314:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
kitematic    | >> No protocol specified
kitematic    | >> [28:0828/212314:ERROR:browser_main_loop.cc(219)] Gtk: cannot open display: :0
kitematic    | >> [30:0100/000000:ERROR:zygote_linux.cc(588)] write: Broken pipe
kitematic    | Warning: Done, with errors: command "/opt/kitematic/node_modules/electron-prebuilt/dist/electron build" (target "electron") exited with code 1.
```
